# Generated by Django 4.2.7 on 2025-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_comment_ad_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
